---
- name: default
  hosts: vyos01
  gather_facts: false

  vars:
    vrf_name:
      - test1

  tasks:
  
    # - name: before show vrf
    #   vyos_command:
    #     commands: "show {{ item.vrf }}"
    #   loop: 
    #     - vrf: 'vrf'
    #     - vrf_name: '{{ vrf | default[test1] }}'
    #   register: result

    # - name: debug result
    #   debug:
    #     var: result.results | list

    # - name: config
    #   vyos_config:
    #     lines:
    #     - set vrf name test1
    #     - set vrf name test1 table 100

    # - name: after show vrf
    #   vyos_command:
    #     commands: "show vrf name test1"
    #   register: result

    # - name: debug result
    #   debug:
    #     msg: "{{ result.stdout_lines[0] }}"