---
- name: regex_serch
  hosts: localhost
  gather_facts: false
  vars:
    sample_data: |
      - test1
      - test2
      - test3
  tasks:
    - name: "search"
      debug:
        msg: "OK"
      loop:
        - "test2"
        - "exam1"
      when:
        - sample_data | regex_search(item)