---
- name: link_bypass
  hosts: vyos
  gather_facts: false

  tasks:
    - name: make directory
      import_role:
        name: make_directory

    - name: get show commands before
      import_role:
        name: get_show_commands
      vars:
        before_or_after: "before"

    - name: assertion
      import_role:
        name: assert_link_bypass

    - name: decrease priority
      import_role:
        name: change_priority
      vars:
        priority: 50
        state: "BACKUP"

    - name: get show commands after
      import_role:
        name: get_show_commands
      vars:
        before_or_after: "after"
