---
- name: link_bypass
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show commands
      vyos_command:
        commands: show interfaces | match 'Interface|eth1|eth2'
      register: result

    - name: debug
      debug:
        msg: "{{ result }}"