---
- name: link_bypass
  hosts: vyos
  gather_facts: false

  tasks:
    - name: reterive show commands
      set_fact:
        show_commands: 
          - "show vrrp"
          - "show version"

    - name: show commands
      vyos_command:
        commands: "{{ item }}"
      loop: "{{ show_commands }}"
      register: result
 
    - name: reterive show commands
      set_fact:
        result_vrrp: "{{ result.results | json_query(\"[?item=='show vrrp'].stdout[0]\") }}"

    - name: debug
      debug:
        msg: "{{ result_vrrp }}"