---
- name: ensyuu5
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show ver
      vyos_command:
        commands: "{{ item }}"
      loop:
        - "show vrrp"
        - "show ver"
        - "show configuration commands"
      register: result
      when: item == "show ver"
     
    - name: debug result
      debug:
       var: result.results|map(attribute='stdout_lines')|list

    - name: show vyos
      vyos_command:
        commands: ['show vrrp','show configuration command']
      register: result_config
      when: inventory_hostname == 'vyos01' or 'vyos02'
        
    - name: make vyos
      file:
        path: /home/ec2-user/yokogushi_contents_team/ansible_practice/{{ item }}
        state: directory
        mode: 0755
      loop: 
        - 'vyos01'
        - 'vyos02'

    - name: copy configuration1
      copy:
        content: "{{ result_config.stdout[0] }}"
        dest: /home/ec2-user/yokogushi_contents_team/ansible_practice/{{ item }}/show_vrrp.log
        mode: 0755 
      when: inventory_hostname == "{{ item }}"
      loop: 
        - 'vyos01'
        - 'vyos02'

    - name: copy configuration2
      copy:
        content: "{{ result_config.stdout[1] }}"
        dest: /home/ec2-user/yokogushi_contents_team/ansible_practice/{{ item }}/show_configuration_command.log
        mode: 0755
      when: inventory_hostname == "{{ item }}"
      loop: 
        - 'vyos01'
        - 'vyos02'

    
        