---
- name: loop_eensyuu4
  hosts: vyos01
  gather_facts: false


  tasks:
    - name: user
      vyos_command:
        commands: show system login users
      register: result

    - name: before users
      debug:
        var: result.stdout_lines

    - name: add users
      vyos_config:
        lines:
          - set system login user "{{ item.name }}"
          - set system login user "{{ item.name }}" authentication plaintext-password "{{ item.password }}"
      loop:
        - {name: 'guest1', password: 'user1'}
        - {name: 'guest2', password: 'user1'}
        - {name: 'guest3', password: 'user1'}

    - name: after user
      vyos_command:
        commands: show system login users
      register: result

    - name: after users
      debug:
        var: result.stdout_lines
