---
- name: loop_exam1
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: add users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - taro
        - hanako
