#Q2 出力結果をloopの中から3つだけ出力させたいとき、■■■にはどんな条件式が入るでしょうか。
---
- name: exam2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: when/loop
      debug: 
        var: item
      loop:
        - 3
        - 10
        - 25
        - 140
        - 233
        - 350
      when: ■■■
