---
- name: exam4
  hosts: vyos
  gather_facts: false

  tasks:
    - name: before show interface
      vyos_command:
        commands:
          - show interfaces
      register: result

    - name: before show interface debug
      debug:
        var: result.stdout_lines

    - name: set descriptions
      vyos_config:
        lines:
          - set interfaces ethernet {{ item.ethernet }} description {{ item.description }}
      loop:
        - { ethernet: 'eth1', description: 'loop_test1' }
        - { ethernet: 'eth2', description: 'loop_test2' }

    - name: after show interface
      vyos_command:
        commands:
          - show interfaces
      register: result

    - name: after show interface debug
      debug:
        var: result.stdout_lines
