---
- name: ensyuu_condition
  hosts: all
  gather_facts: false

  tasks:
    - name: vyos show ip route
      vyos_command:
        commands:
          cmd:  show ip route
      register: result
      when: inventory_hostname in groups['vyos']

    - name: debug result
      debug:
        var: result.stdout_lines
      when: inventory_hostname in groups['vyos']
    
    - name: centos7 route
      command: 
        cmd: route
      register: result
      when: inventory_hostname in groups['centos7']

    - name: centos7 debug result
      debug:
        var: result.stdout_lines
      when: inventory_hostname in groups['centos7']