---
- name: ensyuu_condition
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show ip route
      vyos_command:
        commands: "{{ item }}"
      loop:
        - show ip route
      register: result
      ignore_errors: true
      when: inventory_hostname == 'vyos01' in ['vyos01','vyos02','vyos03']

    - name: debug result
      debug:
        var: result.results|map(attribute='stdout_lines')|list
      when: inventory_hostname == 'vyos01' in ['vyos01','vyos02','vyos03']
