---
- name: ensyuu_condition2
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show ip route
      vyos_command:
        commands: "{{ item }}"
      loop:
        - "show vrrrp"
        - "show ver"
        - "show configuration commands"
      ignore_errors: true
      register: result
      when: inventory_hostname == 'vyos01'

    - name: debug result
      debug:
        var: item.stdout_lines
      loop: "{{ result.results }}"
      when: item is succeeded
    #   when:
    #     - inventory_hostname == 'vyos01'
    #     - result is succeeded

    # - name: debug result
    #   debug:
    #     msg: "{{ result.stdout_lines[2] }}"
    #   when:
    #     - inventory_hostname == 'vyos01'
    #     - result is succeeded

    # - name: debug result
    #   debug:
    #     msg: ng
    #   when:
    #     - inventory_hostname == 'vyos01'
    #     - result is failed