---
- name: when_exam4
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show commands
      vyos_command:
        commands: show interfacess
      ignore_errors: true
      register: result
      when: inventory_hostname == 'vyos01'

    - name: debug
      debug:
        var: result
      when: inventory_hostname == 'vyos01'
