---
- name: exam_3
  hosts: all
  gather_facts: false

  tasks:
    - name: show ip route
      vyos_command:
        commands:
          - show ip route
      when: inventory_hostname in ['vyos01','vyos02']

      