---
- name: when_sample_1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show commands
      vyos_command:
        commands: show ip route
      register: result
      when: inventory_hostname == 'vyos01'

    - name: debug result
      debug:
        var: result.stdout_lines
