---
- name: when_exam3
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show commands
      vyos_command:
        commands: show ip route
      register: result
      ignore_errors: true
      when: inventory_hostname == 'vyos01' in ['a','B','c']

    - name: debug result
      debug:
        var: result.stdout_lines
      when: inventory_hostname == 'vyos01' in ['vyos01','vyos02','vyos03']
