---
- name: sample1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: vyos01 only show commands
      vyos_command:
        commands: 
          - show ip route
          - show interface
      register: result
      when: inventory_hostname == 'vyos01'

    - name: vyos debug show commands
      debug: 
        var: result.stdout_lines
