---
- name: loop_exam4
  hosts: vyos01
  gather_facts: false
  become: true

  tasks:
    - name: user check
      vyos_command:
        commands: show system login users
      register: result

    - name: before users
      debug:
        var: result.stdout_lines

    - name: add users
      vyos_user:
        name: "{{ item.name }}"
        configured_password: "{{ item.password }}"
        state: present
      loop:
        - {name: 'guest1', password: 'pass1'}
        - {name: 'guest2', password: 'pass2'}
        - {name: 'guest3', password: 'pass3'}

    - name: user check
      vyos_command:
        commands: show system login users
      register: result

    - name: after users
      debug:
        var: result.stdout_lines
