---
- name: exam1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show vrrp before
      vyos_command:
        commands: "show vrrp"
      register: result

    - name: vrrp state before
      debug:
        var: result.stdout_lines[0]

    - name: change priority of vrrp
      vyos_config:
        lines:
          - "set high-availability vrrp group service_nw01 priority '50'" #vrrpのプライオリティ値を50に変更
          - "set high-availability vrrp group service_nw02 priority '50'" #vrrpのプライオリティ値を50に変更
        save: true
      when: inventory_hostname == 'vyos01' #vyos01のみ実施

    - name: show vrrp after
      vyos_command:
        commands: "show vrrp"
      register: result

    - name: vrrp state after
      debug:
        var: result.stdout_lines[0]
