---
- name: exam2-1_mode-0775 #問題2-1 パーミッション「0755」で作成した場合 
  hosts: localhost
  gather_facts: false

  tasks:
    - name: make dirictory 
      file:
        path: "{{ playbook_dir }}{{ item }}"
        state: directory
        mode: '0775'
      loop:
        - /before/vyos01
        - /before/vyos02
        - /after/vyos01
        - /after/vyos02
