---
- name: exam2-2_mode-0644  # 問題2-2 問題2-1で作成したディレクトリのパーミッション「0644」のとき
  hosts: vyos
  gather_facts: false
  become: true  # 権限昇格が必要

  tasks:
    - name: show commands vyos
      vyos_command:
        commands:
          - show vrrp
      register: show_result

    - name: debug show commands
      debug:
        var: show_result.stdout_lines

    - name: debug text show commands
      copy:
        content: "{{ show_result.stdout[0] }}"
        dest: /before/{{ inventory_hostname }}/{{ inventory_hostname }}_show_result.txt
        mode: '0644'  # 問題に無いので任意
      delegate_to: localhost  # localhostに対して実行
