---
- name: general-practice1
  hosts: vyos
  gather_facts: false

  tasks:
    - name: before show vrrp
      vyos_command:
        commands:
          - show vrrp
      register: before_vrrp_result

    - name: before show vrrp debug
      debug:
        var: before_vrrp_result.stdout_lines

    - name: set vrrp 150 -> 50
      vyos_config:
        lines:
          - set high-availability vrrp group 'service_nw01' priority '50'
          - set high-availability vrrp group 'service_nw02' priority '50'
      when: inventory_hostname == 'vyos01'

    - name: after show vrrp
      vyos_command:
        commands:
          - show vrrp
      register: after_vrrp_result

    - name: after show vrrp debug
      debug:
        var: after_vrrp_result.stdout_lines
