---
- hosts: localhost
  gather_facts: false
  become: false

  tasks:
  - name: make directory
    file:
      path: /home/ec2-user/yokogushi_contents_team/configure
      state: directory
      mode: 0755
    register: directory_info

  - name: copy configure file
    copy:
      src: /home/ec2-user/yokogushi_contents_team/ansible_practice/yamamoto/vyos_config.txt
      dest: "{{ directory_info.path }}"
      mode: 0655

  - name: delete file
    file:
      path: /home/ec2-user/yokogushi_contents_team/ansible_practice/yamamoto/vyos_config.txt
      state: absent
