---
- hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: register vyos config
      vyos_command:
        commands:
          - show configuration commands
      register: result_config

    - name: save configuration
      copy:
        content: "{{ result_configure.stdout[0] }}"
        dest: /home/ec2-user/yokogushi_contents_team/ansible_practice/yamamoto/vyos_config.txt
        mode: 0644
