---
- name: vyos_exam3
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show interface
      vyos_command:
        commands: show ip route
      register: result

    - name: debug ip route
      debug:
        var: result.stdout_lines
