---
- name: ensyuu3
  hosts: vyos
  gather_facts: false

  tasks:
    - name: get_vrrp
      vyos_command:
        commands: ["show vrrp","show ver","show configuration commands"]
      register: result

    - name: debug result
      debug:
        msg: "{{ result.stdout_lines[0] }}"
      ignore_errors: true
      when: inventory_hostname == vyos1
