---
- name: variable_exercise3
  hosts: localhost
  gather_facts: false

  tasks:
    - name: set_fact
      set_fact:
        test_hostname: "vyos01"

    - name: debug
      debug:
        var: test_hostname
