---
- name: sample2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: sample2 set_fact
      set_fact:
        test: "Hello Ansible!"

    - name: sample2 debug set_fact 
      debug:
        var: test
