---
- name: variable_exercise2
  hosts: vyos01
  gather_facts: false
  
  tasks:
    - name: set_fact
      set_fact:
        ansible_play_name: "Hello Ansible!"

    - name: 
      debug:
        var: ansible_play_name

